### ISSUE TITLE
java.io.IOException: Cannot run program "su": error=13, Permission denied

### ISSUE THREAD

**Issue by feresr** [Juergen12000/AndroidEventInjector#1]
I'm trying to run your code on a rooted device and getting:

`java.io.IOException: Cannot run program "su": error=13, Permission denied`

I added 

> ```
> <uses-permission android:name="android.permission.ACCESS_SUPERUSER"/>
> ```

In the manifest, but still no luck. Could you give me a hand :)

**Comment by jpunz** [comment]
Hey,

are you sure that you've used superuser-shell on your phone?
try to execute the commands, which are implemented in my code, by adb (superuser) shell over pc.

Regards,
Jürgen

**Comment by feresr** [comment]
Hey Jürgen,
it turns out the phone I was using to try this out was't rooted, the bootloader, was unlocked that's all. I tried this on a rooted phone and worked like a charm!

Regards

**Comment by jpunz** [comment]
Great, I way guessing something like that ;)

Jürgen

**Comment by adeach** [comment]
Hai, 
I have same issue, 
I'm getting error in this line itself :  **Process p = Runtime.getRuntime().exec("su");**
Im using rooted device itself, my android version is 10
Please correct me in this issue.

**Comment by patpolster** [comment]
> I'm trying to run your code on a rooted device and getting:
> 
> `java.io.IOException: Cannot run program "su": error=13, Permission denied`
> 
> I added
> 
> > ```
> > <uses-permission android:name="android.permission.ACCESS_SUPERUSER"/>
> > ```
> 
> In the manifest, but still no luck. Could you give me a hand :)

**Comment by Jonathan8GO** [comment]
Do you know if there is a way to fix it without rooting the device?
